//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresupDisponible.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atuevaluacion_demo
    {
        public string CLV_UNIDADM { get; set; }
        public string UNIDADM { get; set; }
        public string TIPO_GASTO { get; set; }
        public string CLV_CAPITULO { get; set; }
        public string CAPITULO { get; set; }
        public string CLV_PARTIDA { get; set; }
        public string PARTIDA { get; set; }
        public string CLV_LOCALIDAD { get; set; }
        public string LOCALIDAD { get; set; }
        public string CLV_FUENTE { get; set; }
        public string FUENTE { get; set; }
        public string ABR_FUENTE { get; set; }
        public string CLV_RECURSO { get; set; }
        public string RECURSO { get; set; }
        public string ID_PROYECTO { get; set; }
        public string PROYECTO { get; set; }
        public string FECHA_INICIO { get; set; }
        public string FECHA_TERMINO { get; set; }
        public string N_PROGRAMA { get; set; }
        public string PROGRAMA { get; set; }
        public string PROG_PRESUP { get; set; }
        public string CLV_EJE { get; set; }
        public string EJE { get; set; }
        public string CLV_PROG_ALIN { get; set; }
        public string PROG_ALIN { get; set; }
        public string CLV_OBJ_ALIN { get; set; }
        public string OBJ_ALIN { get; set; }
        public string CLV_EST_ALIN { get; set; }
        public string EST_ALIN { get; set; }
        public string CLV_LIN_ACC { get; set; }
        public string LIN_ACC { get; set; }
        public string CLV_IND_ALIN { get; set; }
        public string IND_ALIN { get; set; }
        public string CLV_META_ALIN { get; set; }
        public string META_ALIN { get; set; }
        public string CLV_FIN { get; set; }
        public string FINAL { get; set; }
        public string CLV_FUN { get; set; }
        public string FUNCION { get; set; }
        public string CLV_SUBFUN { get; set; }
        public string SUBFUNCION { get; set; }
        public string CLV_ACTINST { get; set; }
        public string ACTIVIDAD_INST { get; set; }
        public string MODEJECUC { get; set; }
        public string MODAINVE { get; set; }
        public Nullable<decimal> INICIAL { get; set; }
        public Nullable<decimal> AMPLIADO { get; set; }
        public Nullable<decimal> REDUCIDO { get; set; }
        public Nullable<decimal> PRESUPUESTO { get; set; }
        public Nullable<decimal> COMPROMETIDO { get; set; }
        public Nullable<decimal> DEVENGADO { get; set; }
        public Nullable<decimal> EJERCIDO { get; set; }
        public Nullable<decimal> PAGADO { get; set; }
        public string ESTADO { get; set; }
    }
}
