//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresupDisponible.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTOS_ANALITICO
    {
        public string CLV_UNIDADM { get; set; }
        public string UNIDADM { get; set; }
        public int CLV_PARTID { get; set; }
        public string PARTIDA { get; set; }
        public Nullable<double> MODIFICADO { get; set; }
        public Nullable<double> ENERO_COM { get; set; }
        public Nullable<double> FEBRERO_COM { get; set; }
        public Nullable<double> MARZO_COM { get; set; }
        public Nullable<double> ABRIL_COM { get; set; }
        public Nullable<double> MAYO_COM { get; set; }
        public Nullable<double> JUNIO_COM { get; set; }
        public Nullable<double> JULIO_COM { get; set; }
        public Nullable<double> AGOSTO_COM { get; set; }
        public Nullable<double> SEPTIEMBRE_COM { get; set; }
        public Nullable<double> OCTUBRE_COM { get; set; }
        public Nullable<double> NOVIEMBRE_COM { get; set; }
        public Nullable<double> DICIEMBRE_COM { get; set; }
        public Nullable<double> OCTUBRE_DIS { get; set; }
        public Nullable<double> NOVIEMBRE_DIS { get; set; }
        public Nullable<double> DICIEMBRE_DIS { get; set; }
    }
}
