//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresupDisponible.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTO_ANALITICOXUNIDAD
    {
        public int ID { get; set; }
        public string CLV_UNIDADM { get; set; }
        public string UNIDADM { get; set; }
        public string CLV_RECURSO { get; set; }
        public string RECURSO { get; set; }
        public string CLV_CAPITU { get; set; }
        public string CAPITULO { get; set; }
        public string N_PROGRAMA { get; set; }
        public string PROG_PRESUP { get; set; }
        public int CLV_PARTID { get; set; }
        public string PARTIDA { get; set; }
        public Nullable<double> MODIFICADO { get; set; }
        public Nullable<double> COMPROMETIDO { get; set; }
        public Nullable<double> OCTUBRE_DIS { get; set; }
        public Nullable<double> NOVIEMBRE_DIS { get; set; }
        public Nullable<double> DICIEMBRE_DIS { get; set; }
        public Nullable<double> ENERO_EJE { get; set; }
        public Nullable<double> FEBRERO_EJE { get; set; }
        public Nullable<double> MARZO_EJE { get; set; }
        public Nullable<double> ABRIL_EJE { get; set; }
        public Nullable<double> MAYO_EJE { get; set; }
        public Nullable<double> JUNIO_EJE { get; set; }
        public Nullable<double> JULIO_EJE { get; set; }
        public Nullable<double> AGOSTO_EJE { get; set; }
        public Nullable<double> SEPTIEMBRE_EJE { get; set; }
        public Nullable<double> OCTUBRE_EJE { get; set; }
        public Nullable<double> NOVIEMBRE_EJE { get; set; }
        public Nullable<double> DICIEMBRE_EJE { get; set; }
    }
}
