//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresupDisponible.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYPRES22
    {
        public int Id { get; set; }
        public string CLV_PROG { get; set; }
        public string PP22 { get; set; }
        public string TIPO_PROY { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CLV_PAR { get; set; }
        public string PARTIDA { get; set; }
        public Nullable<int> IDUNIDAD { get; set; }
        public string UNIDADADM { get; set; }
        public string modmar { get; set; }
        public string RECURSO { get; set; }
        public Nullable<decimal> P2018 { get; set; }
        public Nullable<decimal> P2019 { get; set; }
        public Nullable<decimal> P2020 { get; set; }
        public Nullable<decimal> P2021 { get; set; }
        public Nullable<decimal> NOV21 { get; set; }
        public Nullable<decimal> PROMEDIO { get; set; }
        public Nullable<decimal> IRREDUCTIBLE2022 { get; set; }
        public string OBS { get; set; }
        public Nullable<decimal> PP2022 { get; set; }
        public Nullable<decimal> solicitud { get; set; }
        public Nullable<decimal> ene { get; set; }
        public Nullable<decimal> FEB { get; set; }
        public Nullable<decimal> MAR { get; set; }
        public Nullable<decimal> ABR { get; set; }
        public Nullable<decimal> MAY { get; set; }
        public Nullable<decimal> JUN { get; set; }
        public Nullable<decimal> JUL { get; set; }
        public Nullable<decimal> AGO { get; set; }
        public Nullable<decimal> SEP { get; set; }
        public Nullable<decimal> OCT { get; set; }
        public Nullable<decimal> NOV { get; set; }
        public Nullable<decimal> DIC { get; set; }
        public string TIPOGTO { get; set; }
        public string OBSERVACIONES { get; set; }
    }
}
