//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresupDisponible.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESUMEN_COMPARATIVO
    {
        public string MODMAR { get; set; }
        public decimal PRES18 { get; set; }
        public decimal PRES21 { get; set; }
        public decimal IRREDUCTIBLE { get; set; }
        public decimal OPE { get; set; }
        public decimal PRO { get; set; }
        public decimal PROY { get; set; }
    }
}
