//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresupDisponible.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPARTIDAS
    {
        public string ID_PROYECTO { get; set; }
        public int CLV_PARTID { get; set; }
        public Nullable<double> ENEMOD { get; set; }
        public Nullable<double> FEBMOD { get; set; }
        public Nullable<double> MARMOD { get; set; }
        public Nullable<double> ABRMOD { get; set; }
        public Nullable<double> MAYMOD { get; set; }
        public Nullable<double> JUNMOD { get; set; }
        public Nullable<double> JULMOD { get; set; }
        public Nullable<double> AGOMOD { get; set; }
        public Nullable<double> SEPMOD { get; set; }
        public Nullable<double> OCTMOD { get; set; }
        public Nullable<double> NOVMOD { get; set; }
        public Nullable<double> DICMOD { get; set; }
        public Nullable<double> ENECOMP { get; set; }
        public Nullable<double> FEBCOMP { get; set; }
        public Nullable<double> MARCOMP { get; set; }
        public Nullable<double> ABRCOMP { get; set; }
        public Nullable<double> MAYCOMP { get; set; }
        public Nullable<double> JUNCOMP { get; set; }
        public Nullable<double> JULCOMP { get; set; }
        public Nullable<double> AGOCOMP { get; set; }
        public Nullable<double> SEPCOMP { get; set; }
        public Nullable<double> OCTCOMP { get; set; }
        public Nullable<double> NOVCOMP { get; set; }
        public Nullable<double> DICCOMP { get; set; }
        public Nullable<double> ENEDEV { get; set; }
        public Nullable<double> FEBDEV { get; set; }
        public Nullable<double> MARDEV { get; set; }
        public Nullable<double> ABRDEV { get; set; }
        public Nullable<double> MAYDEV { get; set; }
        public Nullable<double> JUNDEV { get; set; }
        public Nullable<double> JULDEV { get; set; }
        public Nullable<double> AGODEV { get; set; }
        public Nullable<double> SEPDEV { get; set; }
        public Nullable<double> OCTDEV { get; set; }
        public Nullable<double> NOVDEV { get; set; }
        public Nullable<double> DICDEV { get; set; }
        public Nullable<double> ENEEJE { get; set; }
        public Nullable<double> FEBEJE { get; set; }
        public Nullable<double> MAREJE { get; set; }
        public Nullable<double> ABREJE { get; set; }
        public Nullable<double> MAYEJE { get; set; }
        public Nullable<double> JUNEJE { get; set; }
        public Nullable<double> JULEJE { get; set; }
        public Nullable<double> AGOEJE { get; set; }
        public Nullable<double> SEPEJE { get; set; }
        public Nullable<double> OCTEJE { get; set; }
        public Nullable<double> NOVEJE { get; set; }
        public Nullable<double> DICEJE { get; set; }
        public string PROYECTO { get; set; }
        public string PARTIDA { get; set; }
        public string CLV_UNIDADM { get; set; }
        public Nullable<int> CLV_FUENTE { get; set; }
        public Nullable<int> CLV_RECURSO { get; set; }
        public Nullable<int> CLV_CAPITULO { get; set; }
    }
}
