//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresupDisponible.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VtPresupuesto
    {
        public string ID_PROYECTO { get; set; }
        public int CLV_PARTID { get; set; }
        public Nullable<double> ENERO { get; set; }
        public Nullable<double> FEBRERO { get; set; }
        public Nullable<double> MARZO { get; set; }
        public Nullable<double> ABRIL { get; set; }
        public Nullable<double> MAYO { get; set; }
        public Nullable<double> JUNIO { get; set; }
        public Nullable<double> JULIO { get; set; }
        public Nullable<double> AGOSTO { get; set; }
        public Nullable<double> SEPTIEMBRE { get; set; }
        public Nullable<double> OCTUBRE { get; set; }
        public Nullable<double> NOVIEMBRE { get; set; }
        public Nullable<double> DICIEMBRE { get; set; }
        public string MOMENTO { get; set; }
        public string PROYECTO { get; set; }
        public string PARTIDA { get; set; }
        public string CAPITULO { get; set; }
        public string CLV_UNIDADM { get; set; }
        public string UNIDADM { get; set; }
        public Nullable<int> CLV_CAPITULO { get; set; }
        public Nullable<int> CLV_RECURSO { get; set; }
        public string RECURSO { get; set; }
        public string TIPO_GASTO { get; set; }
        public Nullable<int> CLV_FUENTE { get; set; }
        public string FUENTE { get; set; }
    }
}
